#!/bin/bash -e

# remote backup script

# requires passphrase-less SSH login on $SERVER for the user running this

# config

SERVER=remote.example.com
DEST=/var/local/backup/$SERVER	# adjust to your setup
REPOLIST=/var/local/backup/git-repos.txt

# pull the repos
mkdir -p $DEST
cd $DEST

ssh $SERVER cat $REPOLIST |
sed -e '/^#/d; /^$/d' |
while read -r path repo; do
	if [ ! -d $repo ]; then
		git init --bare $repo
		GIT_DIR=$repo git remote add --mirror=fetch origin ssh://$SERVER$path
	fi
	GIT_DIR=$repo git fetch --quiet origin || echo $repo
done
