#!/bin/bash -e

# remote backup script

# requires passphrase-less SSH login on $SERVER for the user running this

# config

SERVER=remote.example.com
DEST=/var/local/backup/$SERVER	# adjust to your setup

# get the list of repos to pull from
GITLIST=/tmp/pull_$$
trap "rm -f $GITLIST" 1 2 3 9 15 ERR EXIT
scp -q $SERVER:/var/local/backup/git-repos.txt $GITLIST

# pull the repos
mkdir -p $DEST
cd $DEST
sed -e '/^#/d; /^$/d' <$GITLIST | while read -r path repo; do
	if [ ! -d $repo ]; then
		git init --bare $repo
		GIT_DIR=$repo git remote add --mirror origin ssh://$SERVER$path
	fi
	GIT_DIR=$repo git fetch --quiet origin
done
